# Generated by Django 3.1 on 2021-07-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalRegistrado',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('nome', models.CharField(max_length=255)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
            ],
        ),
    ]
